### ISSUE TITLE
Deprovisioning fails when node resources exactly equal to provisioner resources

### ISSUE THREAD

**Issue by willthames** [aws/karpenter-core#198]
### Version

__Karpenter Version:__ v0.22.1
__Kubernetes Version:__ v1.23.0

### Expected Behavior

A node using 16cpus should be provisionable as the sole instance in a provisioner with spec.resources.limits set to 16

### Actual Behavior

```
2023-02-01T21:32:42.108Z	INFO	controller.deprovisioning	triggering termination for expired node after TTL	{"commit": "c4a4efd-dirty", "expirationTTL": "720h0m0s", "delay": "421h58m10.108235034s"}
2023-02-01T21:32:42.108Z	INFO	controller.deprovisioning	deprovisioning via expiration replace, terminating 1 nodes redacted/m6i.4xlarge/on-demand and replacing with on-demand node from types m6id.4xlarge, m6i.4xlarge	{"commit": "c4a4efd-dirty"}
2023-02-01T21:32:42.129Z	ERROR	controller.deprovisioning	processing cluster, deprovisioning nodes, launching replacement node, launching machine, cpu resource usage of 16 exceeds limit of 16	{"commit": "c4a4efd-dirty"}
```

### Steps to Reproduce the Problem

Probably create a provisioner with cpu limits exactly equal to node size with a very low ttl and see if the node is deprovisioned after the TTL or not

### Resource Specs and Logs

```
apiVersion: karpenter.sh/v1alpha5
kind: Provisioner
metadata:
  name: bottlerocket-smaller-amd64
spec:
  consolidation:
    enabled: true
  labels:
    architecture: amd64
    base-image: bottlerocket
    worker-group: karpenter-smaller-amd64
  limits:
    resources:
      cpu: "16"
  providerRef:
    name: bottlerocket-general-amd64
  requirements:
  - key: node.kubernetes.io/instance-type
    operator: In
    values:
    - m6i.4xlarge
    - m6id.4xlarge
  - key: kubernetes.io/arch
    operator: In
    values:
    - amd64
  - key: kubernetes.io/os
    operator: In
    values:
    - linux
  - key: karpenter.sh/capacity-type
    operator: In
    values:
    - on-demand
  ttlSecondsUntilExpired: 2592000
  weight: 20
status:
  resources:
    attachable-volumes-aws-ebs: "39"
    cpu: "16"
    ephemeral-storage: 103189828Ki
    memory: 64795788Ki
    pods: "234"
```

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by willthames** [comment]
I believe the problem is https://github.com/aws/karpenter-core/blob/main/pkg/apis/v1alpha5/limits.go#L35 - the `>=` should just be `>` - but I'm not 100% sure

**Comment by njtran** [comment]
Hey @willthames, this happens when the deprovisioning controller decides that a replacement node needs to be spun up for the pods that are going to be evicted. Since a replacement node needs to be initialized before the expired node can be deleted, this means both nodes will be counted towards the limits, which is what i believe you're seeing right now. 

This is expected behavior for the provisioning controller, but this means that your nodes cannot be expired, which is a painful experience.  The trade-off here is availability vs expiration requirements. Karpenter requires the replacement node to be initialized to start deprovisioning the expired node to minimize downtime. In addition, we could make this replacement logic be a special bypass of the limits, but as there could be issues with termination, resulting in a long-term breach of the limits, I'm wary of making a special case like this. It also makes it extremely tough to debug if limits are correctly respected or not in the future.

In the meantime, you should increase your limits to allow some leeway to allow replacement nodes to schedule. This will also help with other complex scheduling constraints you might have (like host-name anti-affinity) that make your nodes not as full.

**Comment by willthames** [comment]
@njtran  sorry, but that logic doesn’t quite fit the error message. If my limit was 17, rather than 16, presumably the node would reprovision. 

16 does not exceed 16, so both the existing function name and the comparison are currently wrong - if you want to turn this into a bigger fix you’re welcome but I think this tiny change suffices here

**Comment by njtran** [comment]
I'm noticing a different problem than what your fix does. Your fix is correct in that the operator should be `>` rather than `>=`.  

A separate discussion, which I'll cut another issue for has to do with the deprovisioning loop. It looks like the error message says it's replacing a .4xlarge with a .4xlarge. Each of those have 16cpus. Since we wait for the replacement to be online, at one point in time during the provisioning loop there will be 32 provisioned vCPUs. This blocks deprovisioning, when really it should just be replaced.
