### ISSUE TITLE
Mutually Exclusive Provisioner Mode

### ISSUE THREAD

**Issue by garvinp-stripe** [aws/karpenter-core#488]
### Description

**What problem are you trying to solve?**
https://aws.github.io/aws-eks-best-practices/karpenter/#create-provisioners-that-are-mutually-exclusive
I am wondering if there is any appetite from Karpenter in supporting a mode where all Provisioners are treated as mutually exclusive. In this mode, Karpenter would take advantage of this and could in theory work a bit quicker since each Provisioner can be worked on in a separate goroutine/ thread for provisioning and deprovisioning and trim down on what each thread evaluates. It could minimize blast radius when a Provisioner is setup incorrect. Lastly, Karpenter could be sharded based on what Provisioner set each replica of Karpenter is managing. 

Similar thought
https://github.com/aws/karpenter/issues/3702

**How important is this feature to you?**
Just throwing thoughts around

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by jonathan-innis** [comment]
> on in a separate goroutine/ thread for provisioning and deprovisioning

Is this mainly a performance concern to help speed up Karpenter's provisioning/deprovisioning? How would you achieve this mutual exclusivity? This would have to be driven at the namespace-level or at the pod-requirements level to shard out the cluster appropriately. It seems difficult for Karpenter to dictate at its level that the cluster is sufficiently sharded without the application-owners themselves assigning the pods to specific provisioners.

I feel like there might be some room to improve performance w.r.t. things like cluster state, where we take global locks that have the potential to slow the performance of the system down. We could potentially do things like shard out the updates and the data so that we can parallelize more of our updates.

**Comment by ellistarn** [comment]
> 1 bad provisioner won't affect everyone else. 

FWIW, we're already designing with this in mind

**Comment by garvinp-stripe** [comment]
> FWIW, we're already designing with this in mind

Awesome!

**Comment by garvinp-stripe** [comment]
> My first thought was around pod requirements where on mutually exclusive mode validation would occur to ensure no overlap however namespaced provisioners sounds like a great way to do it too.

Thinking a bit further. I don't think it is possible to know at provisioner if all provisioners are mutually exclusive because this is based on pods' node selector. So without knowing the entire cluster's world of pods and their node selector this isn't possible. Even with namespaced provisioner, we have the same problem just at the namespace level. However this might not be too bad in that the app owner usually own the namespace so issues would be isolated
